### ISSUE TITLE
Update modulefiles to use latest JEDI Spack-stack

### ISSUE THREAD

**Issue by jiaruidong2017** [NOAA-EMC/GDASApp#390] opened 2023-03-11 13:57 UTC
@CoryMartin-NOAA When building the GDASApp on hera, it crashed with the following errors: 

```
[ 27%] Building Fortran object fms/CMakeFiles/fms.dir/coupler/atmos_ocean_fluxes.F90.o
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms && /apps/oneapi/mpi/2021.5.1/bin/mpiifort -DGFS_PHYS -DINTERNAL_FILE_NML -DSPMD -Dfms_EXPORTS -Duse_LARGEFILE -Duse_libMPI -Duse_netCDF -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/mpp/include -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/fms2_io/include -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/fms -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/include -I/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/netcdf-fortran-4.5.4-6plux7v/include -I/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/netcdf-c-4.8.1-pnwaunu/include -r8 -O2 -g -DNDEBUG  -module module -fPIC -qopenmp -c /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/coupler/atmos_ocean_fluxes.F90 -o CMakeFiles/fms.dir/coupler/atmos_ocean_fluxes.F90.o
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fms/module/atmos_ocean_fluxes_mod.mod fms/CMakeFiles/fms.dir/atmos_ocean_fluxes_mod.mod.stamp Intel
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fms/CMakeFiles/fms.dir/coupler/atmos_ocean_fluxes.F90.o.provides.build
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fms/module/interpolator_mod.mod fms/CMakeFiles/fms.dir/interpolator_mod.mod.stamp Intel
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fms/CMakeFiles/fms.dir/interpolator/interpolator.F90.o.provides.build
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fms/module/xgrid_mod.mod fms/CMakeFiles/fms.dir/xgrid_mod.mod.stamp Intel
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fms/CMakeFiles/fms.dir/exchange/xgrid.F90.o.provides.build
[ 27%] Linking Fortran shared library ../lib/libfms.so
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms && /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E remove /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/lib/libfms.so
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms && /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_link_script CMakeFiles/fms.dir/link.txt --verbose=NO
make[2]: Leaving directory `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build'
[ 27%] Built target fms
make[1]: Leaving directory `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build'
make: *** [all] Error 2
```

**Comment by jiaruidong2017** [comment] 2023-03-11 14:43
I conduct the building `build.sh -t hera` again, it crashed in the different places as below:

```
[ 41%] Building Fortran object fv3-jedi-lm/src/CMakeFiles/fv3jedilm.dir/fv3jedi_lm_mod.F90.o
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fv3-jedi-lm/src && /apps/oneapi/mpi/2021.5.1/bin/mpiifort -DGFS_PHYS -DINTERNAL_FILE_NML -DOLDMPP -DSPMD -DUSE_LOG_DIAG_FIELD_INFO -Dfv3jedilm_EXPORTS -Duse_LARGEFILE -Duse_libMPI -Duse_netCDF -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fv3-jedi-lm/src -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fv3-jedi-lm/src -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fv3-jedi-lm/module -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fms/module -I/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fms/include -I/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/netcdf-fortran-4.5.4-6plux7v/include -I/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/netcdf-c-4.8.1-pnwaunu/include -qopenmp -r8 -O2 -g -DNDEBUG -heap-arrays 32 -module ../module -fPIC -qopenmp -c /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/fv3-jedi-lm/src/fv3jedi_lm_mod.F90 -o CMakeFiles/fv3jedilm.dir/fv3jedi_lm_mod.F90.o
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_copy_f90_mod fv3-jedi-lm/module/fv3jedi_lm_mod.mod fv3-jedi-lm/src/CMakeFiles/fv3jedilm.dir/fv3jedi_lm_mod.mod.stamp Intel
[ 41%] Linking Fortran shared library ../../lib/libfv3jedilm.so
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fv3-jedi-lm/src && /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E remove /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/lib/libfv3jedilm.so
/scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E touch fv3-jedi-lm/src/CMakeFiles/fv3jedilm.dir/fv3jedi_lm_mod.F90.o.provides.build
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build/fv3-jedi-lm/src && /scratch1/NCEPDEV/global/spack-stack/spack-stack-v1/envs/skylab-2.0.0-intel-2021.5.0/install/intel/2021.5.0/cmake-3.22.1-mpovvsm/bin/cmake -E cmake_link_script CMakeFiles/fv3jedilm.dir/link.txt --verbose=NO
make[2]: Leaving directory `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build'
[ 41%] Built target fv3jedilm
make[1]: Leaving directory `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build'
make: *** [all] Error 2
```

**Comment by guillaumevernieres** [comment] 2023-03-11 16:21
@jiaruidong2017 , posting the output of a multi thread build is rarely useful. Instead do this:
```
# load the gdasapp module
cd /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/build
make 
```
and post the error msg.

**Comment by jiaruidong2017** [comment] 2023-03-11 20:52
Thanks @guillaumevernieres for your suggestion. The error messages are as below:

```
[ 13%] Building CXX object oops/src/CMakeFiles/oops.dir/oops/util/FieldSetOperations.cc.o
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/oops/src/oops/util/FieldSetOperations.cc(648): error: class "atlas::FunctionSpace" has no member "gather"
      geometryData.functionSpace().gather(localCoords, globalCoords);
                                   ^

/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/oops/src/oops/util/FieldSetOperations.cc(670): error: class "atlas::FunctionSpace" has no member "gather"
        geometryData.functionSpace().gather(dataField, globalDataField);
                                     ^

/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/oops/src/oops/util/FieldSetOperations.cc(671): error: class "atlas::FunctionSpace" has no member "gather"
        geometryData.functionSpace().gather(diagField, globalDiagField);
                                     ^

compilation aborted for /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.7/oops/src/oops/util/FieldSetOperations.cc (code 2)
make[2]: *** [oops/src/CMakeFiles/oops.dir/oops/util/FieldSetOperations.cc.o] Error 2
make[1]: *** [oops/src/CMakeFiles/oops.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by guillaumevernieres** [comment] 2023-03-11 22:07
Sounds like a problem for Monday @jiaruidong2017 !
Try to build the `feature/stable-nightly` branch, it's only a few commits behind.

**Comment by jiaruidong2017** [comment] 2023-03-11 22:34
Thanks @guillaumevernieres for your efforts, but I do require the latest commit from last Friday for my global-workflow tests.

**Comment by CoryMartin-NOAA** [comment] 2023-03-13 13:05
Looks like this is a problem with something merged into OOPS on Friday that may require a newer version of Atlas loaded... if so, this is going to require a complete update of our modulefiles (annoying). Stay tuned.

**Comment by guillaumevernieres** [comment] 2023-03-13 13:10
> Thanks @guillaumevernieres for your efforts, but I do require the latest commit from last Friday for my global-workflow tests.

I should have written use the hash's from `feature/stable-nightly` for the jedi bundle and develop for the gdasapp @jiaruidong2017 . There is no reason to stay stuck if the issue is in the jedi bundle, unless you are developing in one of the jedi repositories.

**Comment by jiaruidong2017** [comment] 2023-03-13 13:16
@guillaumevernieres Got it, and I will try it. Thanks.

**Comment by jiaruidong2017** [comment] 2023-03-13 13:32
@guillaumevernieres How do I use the hash's from feature/stable-nightly for the jedi bundle and develop for the gdasapp in the global-workflow? The current checkout for the gdasapp in the global-workflow is as below:

```
if [[ ${checkout_gdas} == "YES" ]]; then
  checkout "gdas.cd" "https://github.com/NOAA-EMC/GDASApp.git" "75f7a50"; errs=$((errs + $?))
fi
```

**Comment by guillaumevernieres** [comment] 2023-03-13 13:43
just cherry pick the commit number of the jedi repositories.
Assuming you are in the g-w root dir:
```
cd sorc/gdas.cd
git difftool feature/stable-nightly CMakeLists.txt
```
and just manually pick the commit numbers.

**Comment by jiaruidong2017** [comment] 2023-03-13 13:46
@guillaumevernieres Great help to me. Thanks.

**Closed as completed** 2023-03-13 15:15 UTC
