### ISSUE TITLE
changes to ush/soca/run_jjobs.py incompatible with run_jjobs_hera.yaml

### ISSUE THREAD

**Issue by AndrewEichmann-NOAA** [NOAA-EMC/GDASApp#271] opened 2023-01-11 21:58 UTC
While trying to run the standalone soca j-jobs with a fresh build of GDASApp, I ran into compatibility issues where the new run_jjobs.py choked on my original run_jjobs_hera.yaml.  There are differences between the two versions of run_jjobs.py, though the changes to run_jjobs_hera.yaml don't seem to be significant. The weird thing is that what I started out with and what works doesn't seem to be recorded in the repository, like it got copied from uncommitted/unpushed code. I try to show all this below - I can still run and develop, so nothing urgent.

```
(gdasapp) -bash-4.2$  /scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/split-soca-run/sorc/gdas.cd/ush/soca/run_jjobs.py run_jjobs_hera.yaml
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/split-soca-run/sorc/gdas.cd/ush/soca/run_jjobs.py", line 89, in <module>
    "resdet": exp_config['resdet'],
KeyError: 'resdet'
(gdasapp) -bash-4.2$ diff  /scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/split-soca-run/sorc/gdas.cd/ush/soca/run_jjobs.py  /scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/socarun/sorc/gdas.cd/ush/soca/run_jjobs.py
10c10
< def execute_script(script, exeopt='bash'):
---
> def execute_script((script):
13c13
<         subprocess.check_output([exeopt, script])
---
>         subprocess.check_output(["bash", script])
89c89
<         "resdet": exp_config['resdet'],
---
>         "resdet": exp_config['setup_expt config']['resdet'],
133d132
<     sbatch = 'bash'
136c135
<         sbatch = 'sbatch'
---
>         sbatch = 'sbatch '
138a138
>     sbatch = './'
139a140
>         sbatch = 'sbatch '
154c155
< execute_script(script='run_jjobs.sh', exeopt=sbatch)
---
> execute_script(sbatch+'run_jjobs.sh')
(gdasapp) -bash-4.2$ 
(gdasapp) -bash-4.2$ diff /scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/socarun/sorc/gdas.cd/ush/soca/examples/run_jjobs_hera.yaml /scratch1/NCEPDEV/da/Andrew.Eichmann/fv3gfs/split-soca-run/sorc/gdas.cd/ush/soca/examples/run_jjobs_hera.yaml
1a2
> resdet: 48
33d33
<   resdet: 48
(gdasapp) -bash-4.2$ 

```

**Comment by guillaumevernieres** [comment] 2023-01-11 22:09
@AndrewEichmann-NOAA , you are likely missing the `restdet` key in your yaml.

see here for example: https://github.com/NOAA-EMC/GDASApp/blob/aa8667f3f4f708c7fa98b935b84d823a98c6d267/ush/soca/examples/run_jjobs_hera.yaml#L2

**Comment by guillaumevernieres** [comment] 2023-01-11 22:27
@AndrewEichmann-NOAA , it looks like you are using a commit that isn't develop and has a bug:
This:
```python
"resdet": exp_config['setup_expt config']['resdet'],
```
was corrected to this
```python
"resdet": exp_config['resdet'],
```
and is in `develop` [here](https://github.com/NOAA-EMC/GDASApp/blob/aa8667f3f4f708c7fa98b935b84d823a98c6d267/ush/soca/run_jjobs.py#L89)
The issue is on your side, but happy to go through it with you want ... Closing this issue an patting myself in the back for quickly solving your ticket :)

**Closed as completed by guillaumevernieres** 2023-01-11 22:27 UTC
