### ISSUE TITLE
C48 ATM 3DVar ctest using j-job

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/GDASApp#229] opened 2022-12-05 14:34 UTC
Use FMS ICs stored on Hera/Orion (insert path here later...)

**Comment by CoryMartin-NOAA** [comment] 2022-12-05 16:25
See `$GDASAPP_TESTDATA/lowres/gdas.20210321/12/atmos/RESTART/` for `20210321.180000` RESTART files.
`$GDASAPP_TESTDATA` is now defined in the modulefile

**Comment by RussTreadon-NOAA** [comment] 2022-12-05 19:18
Work for this issue will be done in [`feature/ctest_atm_3dvar`](https://github.com/NOAA-EMC/GDASApp/tree/feature/ctest_atm_3dvar) which originated from `develop` at 4d1cf61

**Comment by guillaumevernieres** [comment] 2022-12-05 21:14
@RussTreadon-NOAA , @CoryMartin-NOAA :

I'm doing the same for the ocean/ice and putting my tests here:
```
...../build/test/soca/global-workflow/testrun
```
Any other preference?

**Comment by CoryMartin-NOAA** [comment] 2022-12-05 21:16
meaning the runtime directory? that seems fine to me.

**Comment by guillaumevernieres** [comment] 2022-12-05 21:17
> meaning the runtime directory? that seems fine to me.

yes.
I'll push my stuff in this branch: ```feature/ctest_ocnice_3dvar```

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 15:47
@guillaumevernieres , @CoryMartin-NOAA   I'm the new kid on the block when it comes to adding ctests.    Should the atm_3dvar test follow the same approach as I see with 0342aa0a in `feature/ctest_ocnice_3dvar`?

**Comment by CoryMartin-NOAA** [comment] 2022-12-06 15:51
@RussTreadon-NOAA looks like it, the new shell scripts that the ctests call basically replace the `jobs/rocoto` shell scripts (but need to have the env vars (e.g. `$HOMEgfs`) that are set by rocoto added to them (probably as a derivative of `$1` and `$2`

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 16:43
Thanks, @CoryMartin-NOAA .   I created and populated `test/atm/global-workflow` in my working copy of `feature/ctest_atm_3dvar`.   Do I need to install a local clone of g-w or is g-w cloned as a ctest.

**Comment by CoryMartin-NOAA** [comment] 2022-12-06 16:45
@RussTreadon-NOAA if running locally you'll need to clone global-workflow yourself, the Github Actions does that as part of its setup

**Comment by CoryMartin-NOAA** [comment] 2022-12-06 17:16
@RussTreadon-NOAA one thing I forgot to mention, you'll need to build GDASApp with `-DWORKFLOW_TESTS=ON`. You can do this through setting the cmake flag, or by `export WORKFLOW_BUILD='ON'` before running the build script.

**Comment by guillaumevernieres** [comment] 2022-12-06 17:44
> @guillaumevernieres , @CoryMartin-NOAA I'm the new kid on the block when it comes to adding ctests. Should the atm_3dvar test follow the same approach as I see with [0342aa0](https://github.com/NOAA-EMC/GDASApp/commit/0342aa0afb747ff85b13e137990a61c72447e874) in `feature/ctest_ocnice_3dvar`?

@RussTreadon-NOAA , definitely recycle the ctest machinery part if you don't have that yet. I've had to change a few thing in the g-w to make things work, as well as define more envar that I thought would have been necessary. Working on cleaning up this afternoon and making use of @aerorahul 's new feature. I tested mine this am off of my g-w PR branch (which is in develop 
 now :tada: ).

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 18:05
Thank you, @CoryMartin-NOAA , for confirming that I'm headed down the right path.  I'm rebuilding with `WORKFLOW_BUILD=ON` in my local environment.    This worked.  I see the `test_gdasapp_atm_jjob_atm_prep` and `test_gdasapp_atm_jjob_atm_run` in the `ctest -N` listing.

Thank you, @guillaumevernieres .  I am working from your soca example.  Your gdasapp4dummy doc is timely.  I foolishly thought setting `WORKFLOW_BUILD=ON` would clone g-w in my local working directory.  I need to switch gears and work on GDASApp inside `gdas.cd` which is inside g-w.

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 19:34
@guillaumevernieres and @CoryMartin-NOAA :  g-w `setup_expt.py` fails to pickup the `yaml` directory in g-w `parm/configs`.  I modified `setup_expt.py` to include the `yaml` directory.   This causes `setup_expt.py` to fail when it attempts to process `yaml` as a file.   I'm working from g-w develop.  Should I be working from a different g-w branch?

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 21:00
@guillaumevernieres  and @CoryMartin-NOAA:  I got past my error.  I added `--yaml $path` as an argument to the `setup_expt.py` command line in `test/atm/global-workflow/setup_workflow_exp.sh`.  I am now working through `unbound variable` exits when `JGDAS_GLOBAL_ATMOS_ANALYSIS_PREP` is executed by ctest `test_gdasapp_atm_jjob_atm_prep`.

**Comment by aerorahul** [comment] 2022-12-06 21:06
@RussTreadon-NOAA 
Apologies for making you "discover" the new `--yaml` option added yesterday.  There is certainly room for improvement in the documentation for the API change in `setup_expt.py`. 
I will let the current sprint end to expose any (possibly many) bugs/limitations in the hastily put solution for customizing configurations.

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 21:24
@aerorahul , I learn better by having things break.  This forces me to dig into the details.   Python still baffles me at times but google guides me to useful references.  I learn and move on.   So thank you for not making things too smooth.

**Comment by RussTreadon-NOAA** [comment] 2022-12-06 21:37
> See `$GDASAPP_TESTDATA/lowres/gdas.20210321/12/atmos/RESTART/` for `20210321.180000` RESTART files. `$GDASAPP_TESTDATA` is now defined in the modulefile

@CoryMartin-NOAA , `GDASAPP_TESTDATA` contains the gdas RESTART for 2021032312.   Where are the observations for 2021032312?

 `JGDAS_GLOBAL_ATMOS_ANALYSIS_PREP` is looking for obs in `/work2/noaa/da/cmartin/GDASApp/R2D2_SHARED/ncdiag/ob/oper_gdas/PT6H`.   This path does not have observations for 2021-03.

**Comment by CoryMartin-NOAA** [comment] 2022-12-06 21:41
@RussTreadon-NOAA ha good catch! Well we need to generate them in IODA format. If we can get operational GSI ncdiags from that date (just in the nick of time for v16, right?) I can run them through the ioda-converters. I guess my question for you is: do you want to learn about this process or would you like me to create them for you?

**Comment by guillaumevernieres** [comment] 2022-12-07 00:25
@RussTreadon-NOAA , @CoryMartin-NOAA , I went over the 128 character limit of fms io ... I suspect you might get close to that as well @RussTreadon-NOAA . Are we allowed to symlink the backgrounds @aerorahul ? If not we might have to change the hard coded limit in fms.
A bit extreme at 135 characters for the base name, but here's my example:
```
/home/gvernier/sandboxes/ctest-sprint/global-workflow/sorc/gdas.cd/build/test/soca/gw/testrun/ROTDIRS/gdas_test/gdas.20180415/06/ocean
```
I'm moving things around, not doing a pr this week in fms, but if we can't symlink it will probably have to be done.

**Comment by RussTreadon-NOAA** [comment] 2022-12-07 00:31
> @RussTreadon-NOAA ha good catch! Well we need to generate them in IODA format. If we can get operational GSI ncdiags from that date (just in the nick of time for v16, right?) I can run them through the ioda-converters. I guess my question for you is: do you want to learn about this process or would you like me to create them for you?

@CoryMartin-NOAA , this is a good chance to learn something new.   I'll get started by pulling operational cnvstat, oznstat, and radstat tarballs off HPSS for the date in question.

**Comment by RussTreadon-NOAA** [comment] 2022-12-07 13:50
> > @RussTreadon-NOAA ha good catch! Well we need to generate them in IODA format. If we can get operational GSI ncdiags from that date (just in the nick of time for v16, right?) I can run them through the ioda-converters. I guess my question for you is: do you want to learn about this process or would you like me to create them for you?
> 
> @CoryMartin-NOAA , this is a good chance to learn something new. I'll get started by pulling operational cnvstat, oznstat, and radstat tarballs off HPSS for the date in question.

2021032118 gdas cnvstat, oznstat, and radstat are now on Hera and Orion and ready for processing.

**Comment by CoryMartin-NOAA** [comment] 2022-12-07 13:57
@RussTreadon-NOAA excellent!

GDASApp includes the ioda-converters repo (iodaconv/). Within this repo, take a look at `src/gsi-ncdiag/proc_gsi_ncdiag.py`. This will be in `build/bin` for execution of IODA-converters. 

Usage is: `./proc_gsi_ncdiag.py -o /path/to/output /path/to/diags`
This script should process all nc-diags in the directory and produce IODA observation files and write them to the path specified by -o.

There is  also a `combine_obsspace` script that will combine sondes_t, sondes_uv, etc. into 'sondes'.

Note: these scripts may need the following done to work properly (not sure):
`export PYTHONPATH=$PYTHONPATH:/path/to/gdasapp/build/lib/pyiodaconv`
`export PYTHONPATH=$PYTHONPATH:/path/to/gdasapp/build/lib/python3.7/pyioda`

**Comment by CoryMartin-NOAA** [comment] 2022-12-07 16:19
@guillaumevernieres I think then that might mean we will want to use relative paths in the YAML? So that we can copy from the shell/python scripts to `${DATA}/bkg` but then just use `bkg/mom6.restart.nc` in the YAML file?

**Comment by RussTreadon-NOAA** [comment] 2022-12-07 16:37
`test_gdasapp_atm_jjob_atm_prep` now passes after several hacks which need to be cleaned up.   I'll leave 'em in place for the time being and move onto `test_gdasapp_atm_jjob_atm_run`.

**Comment by guillaumevernieres** [comment] 2022-12-07 17:29
> @guillaumevernieres I think then that might mean we will want to use relative paths in the YAML? So that we can copy from the shell/python scripts to `${DATA}/bkg` but then just use `bkg/mom6.restart.nc` in the YAML file?

Unless I messed up, the background are in the `ROTDIR` while the scratch for the run is in `RUNDIR`, so relative path won't help ... Muddy brain right now. It's working, so I'm burring that issue deep in my subconscious.

**Comment by RussTreadon-NOAA** [comment] 2022-12-08 16:20
Not sure why but running operational diagnostic files for 2021032318 through `gdas.cd/ush/proc_ops2r2d2.sh` created a sondes ioda file which `fv3jedi_var.x` processed.   `fv3jedi_var.x` ran to completion.    `gdas.cd/ush/jediinc2fv3.py` failed because `gdas.t12z.atmf006.nc` does not exist.  I need to create this file.

**Comment by CoryMartin-NOAA** [comment] 2022-12-08 16:34
@RussTreadon-NOAA huh, interesting. There must have been something I forgot that was some key detail. Glad it is resolved.

**Comment by RussTreadon-NOAA** [comment] 2022-12-08 16:54
> @RussTreadon-NOAA huh, interesting. There must have been something I forgot that was some key detail. Glad it is resolved.

`fv3jedi_var.x` still chokes on the `amsua_n19` ioda file.   I need to dig into the converter to figure out how to force all field output to be float.   Currently the  amsua_n19 ioda file contains

```
group: ObsError {
  variables:
        double brightness_temperature(nlocs, nchans) ;
```

**Comment by CoryMartin-NOAA** [comment] 2022-12-08 17:00
This sounds vaguely familiar. I think the ops ncdiags do write out double for a few fields for the radiances... 

I think the fix could be:
See how this line: https://github.com/JCSDA-internal/ioda-converters/blob/f7f1efffafaba750bd33e14ed78d0df45e17c620/src/gsi-ncdiag/gsi_ncdiag.py#L1384
does int32,
Do the same the previous line, but float32.

**Comment by RussTreadon-NOAA** [comment] 2022-12-08 18:33
> This sounds vaguely familiar. I think the ops ncdiags do write out double for a few fields for the radiances...
> 
> I think the fix could be: See how this line: https://github.com/JCSDA-internal/ioda-converters/blob/f7f1efffafaba750bd33e14ed78d0df45e17c620/src/gsi-ncdiag/gsi_ncdiag.py#L1384 does int32, Do the same the previous line, but float32.

Thank you @CoryMartin-NOAA !   This did the trick.    `test_gdasapp_atm_jjob_atm_run` successfully ran `fv3jedi_var.x`.   `jediinc2fv3.py` fails because I do not have the required `atmf006.nc` input.

**Comment by RussTreadon-NOAA** [comment] 2022-12-08 20:07
Add copies for the following files to `test/atm/global-workflow/jjob_prep.sh`
- `gdas.t12z.atmf006.nc` - used by `jediinc2fv3.py`
- `gdas.t12z.abias*` - `exgdas_global_atmos_analysis_run.sh` copies guess bias correction files to current cycle.   This is an ugly hack until `fv3jedi_var.x` cycles the radiance and aircraft bias correction files.

With these changes and a few other hacks `test_gdasapp_atm_jjob_atm_prep` and `test_gdasapp_atm_jjob_atm_run` successfully run to completion.   

Now onto  `test_gdasapp_atm_jjob_atm_post`.

**Comment by RussTreadon-NOAA** [comment] 2022-12-09 11:29
ATM 3dvar prep, run, and post ctests successfully run to completion when executed from Orion command line.    Changes committed at 2af2696.   Now need to clean up.

**Comment by RussTreadon-NOAA** [comment] 2022-12-09 21:09
The following sequence runs without error on Orion when executed via the command line

- `test_gdasapp_setup_atm_cycled_exp`
- `test_gdasapp_atm_jjob_atm_prep`
- `test_gdasapp_atm_jjob_atm_run`
- `test_gdasapp_atm_jjob_atm_post`

Automated _Unit Tests Within NCEP Global-Workflow_ triggered by `git push` fail when executing the atm_jjob_atm jobs.   @CoryMartin-NOAA and @guillaumevernieres, do I need to push datasets to a server for these tests to pass?

**Comment by CoryMartin-NOAA** [comment] 2022-12-09 21:11
@RussTreadon-NOAA are they wrapped in a `BUILD_GDASBUNDLE` `if` in the CMakeLists.txt? Since they require executable and test data, they won't be able to run on GitHub Actions.

**Comment by RussTreadon-NOAA** [comment] 2022-12-09 21:24
@CoryMartin-NOAA , yes that's my problem.   `test/atm/CMakeLists.txt` has the atm g-w tests inside a `WORKFLOW_TESTS` block but this block sits outside a `BUILD_GDASBUNDLE` block.   Let me move the atm g-w tests inside the `BUILD_GDASBUNDLE` block.

**Comment by RussTreadon-NOAA** [comment] 2022-12-10 20:43
[feature/ctest_atm_3dvar](https://github.com/NOAA-EMC/GDASApp/tree/feature/ctest_atm_3dvar) at 0551de7 is currently two commits behind the current head ([74b9c1d](https://github.com/NOAA-EMC/GDASApp/commit/74b9c1d9d0263b88ce84a0382b5da9cd856258e5)) of [develop](https://github.com/NOAA-EMC/GDASApp/tree/develop).   The atm 3dvar ctests successfully run to completion when built from 0551de7.   

When 74b9c1d develop is merged into feature/ctest_atm_3dvar, `test_gdasapp_atm_jjob_atm_run` fails when `ush/get_obs_list.py` processes `fv3jedi_var.yaml`.  The traceback is shown below:

```
1300: Traceback (most recent call last):
1300:   File "/work/noaa/da/Russ.Treadon/git/global_workflow/ctest_atm_3dvar/sorc/gdas.cd/ush/get_obs_list.py", line 43, in <module>
1300:     get_obs_list(args.config, args.output)
1300:   File "/work/noaa/da/Russ.Treadon/git/global_workflow/ctest_atm_3dvar/sorc/gdas.cd/ush/get_obs_list.py", line 23, in get_obs_list
1300:     obs_list = all_config_dict['cost function']['observations']['observers']
1300: TypeError: string indices must be integers
```
A comparison of the 0551de7 and post-merge feature/ctest_atm_3dvar `fv3jedi_var.yaml` shows that while the 0551de7 has an expanded `observations:` section,

```
    npz: '127'
    ntiles: '6'
  observations:
    observers:
    - get values:
        interpolation method: barycentric
      obs bias:
        covariance:
...
```

 the post-merge `fv3jedi_var.yaml` only has
```
    npz: $(npz_ges)
  observations: /work/noaa/da/Russ.Treadon/git/global_workflow/ctest_atm_3dvar/sorc/gdas.cd/test/atm/global-workflow/gdas_prototype.yaml
  window begin: '2021-03-23T15:00:00Z'
```
This problematic.   `gdas_prototype.yaml` contains unexpanded variables

```
observers:
- $<< $(OBS_YAML_DIR)/amsua_n19.yaml
```

It seems additional changes are needed after merging develop at 74b9c1d  into `feature/ctest_atm_3dvar`.

**Comment by aerorahul** [comment] 2022-12-10 23:05
@CoryMartin-NOAA 
Something is not working as expected when expanding the variables and looking at the example from the comment 
```
 npz: '127'
    ntiles: '6'
  observations:
    observers:
    - get values:
        interpolation method: barycentric
      obs bias:
        covariance:
```
implies that when this is loaded `npz` will be a `str` with value `127`.  Likewise for `ntiles`.   This should not happen and is likely a result of wrapping the template variable in `' '`.  
We can try to write a simple test and figure out the problem in the code, rather than keep using it in a manner it should not.

**Comment by CoryMartin-NOAA** [comment] 2022-12-11 15:11
@RussTreadon-NOAA I think you need to change `$<<` to `!INC` and `$(OBS_YAML_DIR)` to `${OBS_YAML_DIR}`.

@aerorahul I have noticed this with my old parser, it assumes everything is a `str` because it needs to do so to do find/replace. So then there needs to be some sort of 'cleanup' step that converts to float/int (not sure how possible this is though...)

**Comment by RussTreadon-NOAA** [comment] 2022-12-11 20:22
Hmm, this is interesting.  I see
```
observers:
- !INC ${OBS_YAML_DIR}/amsua_n19.yaml
- !INC ${OBS_YAML_DIR}/sondes.yaml
- !INC ${OBS_YAML_DIR}/atms_n20.yaml
- !INC ${OBS_YAML_DIR}/aircraft.yaml
```
in `parm/atm/obs/lists/gdas_prototype.yaml`

`temp.yaml` in the run directory contains
```
  OBS_LIST: /work/noaa/da/Russ.Treadon/git/global_workflow/ctest_atm_3dvar/sorc/gdas.cd/test/atm/global-workflow/gdas_prototype.yaml
  OBS_YAML_DIR: /work/noaa/da/Russ.Treadon/git/global_workflow/ctest_atm_3dvar/sorc/gdas.cd/parm/atm/obs/config/
```
`fv3jedi_var.yaml` contains

` observations: /work/noaa/da/Russ.Treadon/git/global_workflow/ctest_atm_3dvar/sorc/gdas.cd/test/atm/global-workflow/gdas_prototype.yaml
 `
 
Let me experiment with `ush/genYAML` and `ush/get_obs_list.py` tomorrow.  This testing can be done via the command line.

**Comment by RussTreadon-NOAA** [comment] 2022-12-11 21:01
Here's the section of g-w `scripts/exgdas_global_atmos_analysis_run.sh` which creates `temp.yaml` and `fv3jedi_var.yaml` and then processes `fv3jedi_var.yaml` 
```
################################################################################
# generate YAML file
cat > $DATA/temp.yaml << EOF
template: ${ATMVARYAML}
output: $DATA/fv3jedi_var.yaml
config:
  atm: true
  BERROR_YAML: $BERROR_YAML
  OBS_DIR: obs
  DIAG_DIR: diags
  CRTM_COEFF_DIR: crtm
  BIAS_IN_DIR: obs
  BIAS_OUT_DIR: bc
  OBS_PREFIX: $OPREFIX
  BIAS_PREFIX: $GPREFIX
  OBS_LIST: $OBS_LIST
  OBS_YAML_DIR: $OBS_YAML_DIR
  BKG_DIR: bkg
  fv3jedi_staticb_dir: berror
  fv3jedi_fix_dir: fv3jedi
  fv3jedi_fieldset_dir: fv3jedi
  fv3jedi_fieldmetadata_dir: fv3jedi
  OBS_DATE: '$CDATE'
  BIAS_DATE: '$GDATE'
  ANL_DIR: anl/
  NMEM_ENKF: '$NMEM_ENKF'
  INTERP_METHOD: '$INTERP_METHOD'
EOF
$GENYAML --config $DATA/temp.yaml

################################################################################
# link observations to $DATA
$GETOBSYAML --config $DATA/fv3jedi_var.yaml --output $DATA/${OPREFIX}obsspace_list
```

Does something need to be changed in `exgdas_global_atmos_analysis_run.sh`?

**Comment by CoryMartin-NOAA** [comment] 2022-12-11 21:21
`$GENYAML` and `$GETOBSYAML` probably need to be modified to use `pygw`'s utilities.  I can look into it tomorrow.

**Comment by RussTreadon-NOAA** [comment] 2022-12-11 21:27
Thanks, @CoryMartin-NOAA .  Good to have a starting point for this week's work.

**Comment by guillaumevernieres** [comment] 2022-12-12 00:38
> Thanks, @CoryMartin-NOAA . Good to have a starting point for this week's work.

I've always had to "clean" the yamls @RussTreadon-NOAA (https://github.com/NOAA-EMC/GDASApp/blob/74b9c1d9d0263b88ce84a0382b5da9cd856258e5/scripts/exgdas_global_marine_analysis_run.sh#L81). Good enough for now but we should probably add a "TODO" ...

**Comment by RussTreadon-NOAA** [comment] 2022-12-12 16:38
g-w PR [#1106](https://github.com/NOAA-EMC/global-workflow/pull/1106) adds [`ush/python/pygfs`](https://github.com/NOAA-EMC/global-workflow/tree/feature/aeroda_staticb_crm/ush/python/pygfs).  This directory contains [`task/aero_analysis.py`](https://github.com/NOAA-EMC/global-workflow/blob/feature/aeroda_staticb_crm/ush/python/pygfs/task/aero_analysis.py).  This script defines `npx_anl`, `npy_anl`, and `npz_anl` as well as the `_ges` variants of these variables for the aero app.    It looks like we need to add a atm equivalent to `aero_analysis.py`.  We should merge PR [#1106](https://github.com/NOAA-EMC/global-workflow/pull/1106) into g-w develop first and extend `pygfs` to cover the atm application.

**Comment by RussTreadon-NOAA** [comment] 2022-12-12 21:20
If I update [feature/ctest_atm_3dvar](https://github.com/NOAA-EMC/GDASApp/tree/feature/ctest_atm_3dvar) to the head of GDASApp develop, atm g-w tests no longer work.   We need to add the GDASApp atm mode to g-w `pygfs`.   When do we expect g-w PR #1106 to be merged into develop?   

@CoryMartin-NOAA , @guillaumevernieres , @aerorahul :  Thoughts on the best path forward?

**Comment by CoryMartin-NOAA** [comment] 2022-12-12 21:26
@RussTreadon-NOAA I am hoping to get that PR tidied up tomorrow (today was crazy unfortunately with meetings and emails), I at least have the whole afternoon blocked off. I have two suggestions:
1) the short term solution, make small changes to the GDASApp/ush/ufsda tools to use the pygw YAML tools and not the ufsda ones
2) the long term solution, do what you described. 1 will also require 2 to be done but makes the timelines a bit more relaxed.

Thoughts?

**Comment by RussTreadon-NOAA** [comment] 2022-12-12 21:36
@CoryMartin-NOAA , let me try the short term solution tomorrow.   gsi global regression tests sidetracked me this afternoon.

**Comment by guillaumevernieres** [comment] 2022-12-12 21:46
"Spiral" development (I was going to write circular ... but hopefully not!) is what we should be aiming for @RussTreadon-NOAA and @CoryMartin-NOAA , gradual tested improvement. The target is perfection, but the path to perfection will include annoying hacks ... well ... hacks rarely bother me ... but ... fine ...

**Comment by RussTreadon-NOAA** [comment] 2022-12-14 14:18
@CoryMartin-NOAA , your changes in [`feature/atm_pygw_yamls`](https://github.com/NOAA-EMC/GDASApp/tree/feature/atm_pygw_yamls) work.   The atm 3dvar ctests run from your branch generate identical results to those run from `feature/ctest_atm_3dvar`.     

We can either merge `feature/atm_pygw_yamls` into `feature/ctests_atm_3dvar` or move forward from `feature/atm_pwgw_yamls`.   Any preference?

**Comment by CoryMartin-NOAA** [comment] 2022-12-14 14:19
You did 95% of the work, I suggest merging my branch into yours and then we can issue a PR to develop once it's ready. Does that work for you?

**Comment by RussTreadon-NOAA** [comment] 2022-12-14 14:21
This works, but the 5% you did got us over the finish line.   Thank you!

**Comment by CoryMartin-NOAA** [comment] 2022-12-14 14:23
I will say it is a bit of a temporary hack, a majority of the top level YAML that is created in the workflow ex-script, for example, goes unused. But we should merge these tests in and then clean both GDASApp and global-workflow if/when we transition the ATM scripts to look more like my python-based AERO scripts.

**Closed as completed** 2022-12-17 18:44 UTC
